GET http://localhost:2121/video/get
####
POST http://localhost:2121/video/post HTTP/1.1
Content-Type: application/json

{
    "title": "titolo5",
    "categoryWork": "meccanico",
    "video": "video link2",
    "content": "cambia pezzi",
    "author": "653939363261fc335639fbd1"
}

####
DELETE http://localhost:2121/video/delete/6537a927a3bcc7a04fd0fe13


####
POST http://localhost:2121/users2/post HTTP/1.1
Content-Type: application/json

{
    "name": "quattro",
    "lastName": "QUATTRO",
    "email": "celegabor@gmail.com",
    "dob": "1990-01-21", 
    "address": "via giovanni prati",
    "avatar": "https://png.pngtree.com/element_our/png/20181206/users-vector-icon-png_260862.jpg",
    "password": "password mia"
}
####

POST http://localhost:2121/video/6539530f3261fc335639fd4b/comment/post HTTP/1.1
Content-Type: application/json

{
    "comment": "primo  commento",
    "author": "653939363261fc335639fbd1",
    "videoId": "6539530f3261fc335639fd4b"
}

####

